#!/bin/bash
pushd tmp;
#ffmpeg -start_number 0 -i frame-%04d.jpg -vcodec mpeg4 test.mpg
ffmpeg -r 1 -start_number 0 -i frame-%04d.jpg -f mpjpeg -r 1 http://127.0.0.1:9000
#ffmpeg -i test.mpg -f mjpeg -r 1 http://127.0.0.1:4800
#for (( ; ; ))
#do
#ffmpeg -i out.mp4  -ss 0 -f mjpeg -r 5 http://127.0.0.1:4801
#done
#ffmpeg -framerate 2 -i 'frame-%04d.jpg' out.mp4
#popd;