#!/bin/bash
build_jnihdr
cmake -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --target INSTALL --config Release
#cp lib/apriltagsim.dll ../../wpilib/libs2
#cp lib/apriltag.dll ../../wpilib/libs
#cp lib/apriltag.lib ../../wpilib/libs


