#!/bin/bash
#javac --source-path "$GZ_SIM/gzsim/java" -cp "$GZ_SIM/bin/opencv-java-4.5.2-1.jar;$GZ_SIM/gzsim/java" -h include $GZ_SIM/gzsim/java/utils/TagDetectorJNI.java
#javac apriltag/TagDetectorJNI.java  
#java -Xlog:nmethod* $GZ_SIM/gzsim/java/utils/TagDetectorJNI
#java  apriltag/TagDetectorJNI
java -cp "$GZ_SIM/bin/opencv-java-4.5.2-1.jar;$GZ_SIM/gzsim/java" $GZ_SIM/gzsim/java/utils/TagDetectorJNI.java
