#!/bin/bash
rm -f tmp/*;

#gazebo --verbose simcompbot-empty-field.world &
gazebo  --verbose simcompbot-2023-field.world &
#gazebo -u --verbose simcompbot-cone.world &
#gazebo -u --verbose simcompbot-cube.world &
#gazebo --verbose temp.world &



