#!/bin/bash
gradlew extractReleaseNative 
cp $GZ_SIM/wpilib/libs/apriltag.dll build/jni/release/
cp $GZ_SIM/wpilib/libs/apriltagjni.dll build/jni/release/

export PATH="build/jni/release;$PATH"
gradlew simulateJavaRelease
