#!/bin/bash
rm -f tmp/*;

#gazebo --verbose simswervebot-empty-field.world &
#gazebo --verbose simswervebot-with-perim-tags-1.world &
#gazebo --verbose simswervebot-with-front-tags.world &
gazebo --verbose simswervebot-with-single-tag.world &

#gazebo --verbose simswervebot-2023-Field.world &

#gazebo --verbose temp.world &



