#!/bin/bash
rm -f tmp/*;
# note: also need to change "type" in TargetMgr as follows:
# field-tags       FIELD_TAGS
# perim-tags-1,2   PERIMETER_TAGS
# front-tags       FRONT_TAGS
# single-tags      SINGLE_TAG
# empty-field      NO_TAGS

#gazebo  --verbose simswervebot-empty-field.world &
#gazebo  --verbose simswervebot-with-front-tags.world &
#gazebo  --verbose simswervebot-with-perim-tags-1.world &
#gazebo  --verbose simswervebot-with-single-tag.world &
gazebo  --verbose simswervebot-with-field-tags.world &




