#!/bin/bash
export CENTER=0
export LEFT=1
export RIGHT=2

export POSITION=$RIGHT

if [ "$#" -eq 1 ]; then
    export POSITION="$1"
fi

echo position=$POSITION
start_gazebo --verbose &
GzProgram.exe &
start_dashboard &
sleep 2
simulate &
