/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apriltag_jni_TagDetectorJNI */

#ifndef _Included_apriltag_jni_TagDetectorJNI
#define _Included_apriltag_jni_TagDetectorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     apriltag_jni_TagDetectorJNI
 * Method:    detector_create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_apriltag_jni_TagDetectorJNI_detector_1create
  (JNIEnv *, jobject, jint);

/*
 * Class:     apriltag_jni_TagDetectorJNI
 * Method:    detector_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_apriltag_jni_TagDetectorJNI_detector_1destroy
  (JNIEnv *, jobject);

/*
 * Class:     apriltag_jni_TagDetectorJNI
 * Method:    detector_detect
 * Signature: (JIIDDDDD)[Lapriltag/jni/TagResult;
 */
JNIEXPORT jobjectArray JNICALL Java_apriltag_jni_TagDetectorJNI_detector_1detect
  (JNIEnv *, jobject, jlong, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     apriltag_jni_TagDetectorJNI
 * Method:    detector_image_test
 * Signature: (JIIZZ)V
 */
JNIEXPORT void JNICALL Java_apriltag_jni_TagDetectorJNI_detector_1image_1test
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
