/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_TagDetectorJNI */

#ifndef _Included_utils_TagDetectorJNI
#define _Included_utils_TagDetectorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_TagDetectorJNI
 * Method:    detector_create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_utils_TagDetectorJNI_detector_1create
  (JNIEnv *, jobject, jint);

/*
 * Class:     utils_TagDetectorJNI
 * Method:    detector_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_utils_TagDetectorJNI_detector_1destroy
  (JNIEnv *, jobject);

/*
 * Class:     utils_TagDetectorJNI
 * Method:    detector_detect
 * Signature: (JIIDDDDD)[Lutils/TagResult;
 */
JNIEXPORT jobjectArray JNICALL Java_utils_TagDetectorJNI_detector_1detect
  (JNIEnv *, jobject, jlong, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     utils_TagDetectorJNI
 * Method:    detector_image_test
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_utils_TagDetectorJNI_detector_1image_1test
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
